<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<Version>1.0.2</Version>
		<PackageReleaseNotes>v1.0.2 - Dependency update</PackageReleaseNotes>
		<Authors>LostBeard</Authors>
		<Title>SpawnDev.SpawnJS.RazorUI</Title>
		<Description>A small, themeable UI component library for SpawnDev.SpawnJS.RazorRenderer.</Description>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<EmbedAllSources>true</EmbedAllSources>
		<DebugType>Embedded</DebugType>
		<PackageProjectUrl>https://github.com/LostBeard/SpawnDev.SpawnJS.RazorRenderer</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageIcon>icon-128.png</PackageIcon>
		<RepositoryUrl>https://github.com/LostBeard/SpawnDev.SpawnJS.RazorRenderer.git</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>DotNetWebAssembly;Browser</PackageTags>
		<NoPackageAnalysis>true</NoPackageAnalysis>
		<EnableDefaultCompileItems>true</EnableDefaultCompileItems>
		<IsPackable>true</IsPackable>
		<LangVersion>latest</LangVersion>
		
		<!-- Serve wwwroot at / -->
		<StaticWebAssetBasePath Condition="'$(StaticWebAssetBasePath)' == ''">/</StaticWebAssetBasePath>

		<!-- Generated CSS will be fingerprinted if not disabled -->
		<StaticWebAssetFingerprintingEnabled>false</StaticWebAssetFingerprintingEnabled>
		<StaticWebAssetsFingerprintContent>false</StaticWebAssetsFingerprintContent>
		<!-- Disable compression (optional, based on use case) -->
		<CompressionEnabled>false</CompressionEnabled>
	</PropertyGroup>

	<ItemGroup>
		<None Include="Images\icon-128.png" Pack="true" PackagePath="\" />
		<None Include="..\LICENSE.txt" Pack="true" PackagePath="\" />
		<None Include="..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.10" />
	</ItemGroup>

	<!-- ProjectReference used for Debug builds -->
	<ItemGroup Condition=" '$(Configuration)' == 'Debug' ">
		<ProjectReference Include="..\SpawnDev.SpawnJS.RazorRenderer\SpawnDev.SpawnJS.RazorRenderer.csproj"  />
	</ItemGroup>

	<!-- PackageReference used for Release builds -->
	<ItemGroup Condition=" '$(Configuration)' == 'Release' ">
		<PackageReference Include="SpawnDev.SpawnJS.RazorRenderer" Version="1.0.5"  />
	</ItemGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

</Project>
