using RazorRendererDemo;
using RazorRendererDemo.Services;
using SpawnDev;
using SpawnDev.SpawnJS;
using SpawnDev.SpawnJS.JSObjects;
using SpawnDev.SpawnJS.RazorRenderer;
using SpawnDev.SpawnJS.RazorUI;
using SpawnDev.SpawnJS.WebWorkers;
using System.Diagnostics;
using System.Runtime.InteropServices.JavaScript;

// SpawnJSApp is a minimal DI container with SpawnJSRuntime and BackgroundServiceManager.
var builder = SpawnJSAppBuilder.CreateDefault(args, out var JS);


{
    var sw = Stopwatch.StartNew();
    var array = JS.New("Array");
    JS.Set("_marray", array);
    var cnt = 10000;
    var callsPerIteration = 2;
    for (var i = 0; i < cnt; i++)
    {
        using var window2 = JS.Get<JSObject>("window");
        array.Set(i, window2);
    }
    var callCountTotal = callsPerIteration * cnt;
    var costPerCall = sw.Elapsed.TotalMicroseconds / (cnt * callsPerIteration); // 2 calls per iteration, teh window get and the array index set
    var elapsed = sw.Elapsed.TotalMicroseconds;
    Console.WriteLine($"BlazorJS Total .Net to JS calls: {callCountTotal} Cost per call: {costPerCall} microseconds - Total elapsed: {elapsed} microseconds");
    // 2026-08-11 SpawnJS  Total .Net to JS calls: 20000 Cost per call:  3.135 microseconds - Total elapsed:   62700 microseconds
    // 2026-08-11 BlazorJS Total .Net to JS calls: 20000 Cost per call: 91.285 microseconds - Total elapsed: 1825700 microseconds
}

// easy way to detect if we are running in a browser extension content script
var appBaseUri = new Uri(JS.AppBaseUri);
var isBrowserExtensionContentScript = JS.GlobalScope == GlobalScope.Window && appBaseUri.Scheme.Contains("-extension");

// We'll add components based what the environment is detected
if (isBrowserExtensionContentScript)
{
    // When running as browser extension content script we'll render Apptray.razor instead of an App.razor
    // And we'll add styling to the host itself that will be created to handle the ShadowRoot so it renders out-of-line from the website's own elements
    builder.RootComponents.Add<AppTray>(new AttachShadowRootOptions { Mode = "open" }).SetHostStyle("position: fixed; top: 0; left: 50%; z-index: 65536;");
}
else
{
    // Add root components
    builder.RootComponents.Add<App>(new AttachShadowRootOptions { Mode = "open" });
}

// Add stylesheets. Here adding an app supplied css and the app's autogenerated razor css
builder.RootComponents.AddSharedStyleSheet("css/app.cs", "RazorRendererDemo.styles.css");

// register WebWorkerService
builder.Services.AddWebWorkerService();

// register the interactive Razor renderer (SpawnDomRenderer singleton)
builder.Services.AddRazorRenderer();

// register RazorUI (themeable component library on top of the renderer)
builder.Services.AddRazorUI();

// Additional services
builder.Services.AddSingleton<AppService>();

// HTTPClient set to the app's base address 
builder.Services.AddSingleton(sp => new HttpClient { BaseAddress = new Uri(JS.AppBaseUri) });

// SpawnJSRunAsync autostarts IBackgroundService and IAsyncBackgroundService services
// and can take a method that runs after all auto-starting services are started
await builder.Build().RunAsync();
