<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<!-- Disable compression (optional, based on use case) -->
		<CompressionEnabled>false</CompressionEnabled>
		<!-- Disables the Hot Reload background client for WASM -->
		<WasmEnableHotReload>false</WasmEnableHotReload>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="SpawnDev.SpawnJS.WebWorkers" Version="1.0.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SpawnDev.SpawnJS.RazorRenderer\SpawnDev.SpawnJS.RazorRenderer.csproj" />
		<ProjectReference Include="..\SpawnDev.SpawnJS.RazorUI\SpawnDev.SpawnJS.RazorUI.csproj" />
	</ItemGroup>

</Project>
